### ISSUE TITLE
Swift SDK

### ISSUE THREAD

**Issue by NickEckert** [RohanNagar/thunder#10]
Would be nice to have a thunder SDK that handles requests and user account interaction

**Comment by RohanNagar** [comment]
I think it should be possible to take out [ThunderRouter](https://github.com/SanctionCo/pilot-ios/blob/master/pilot/ThunderRouter.swift) from Pilot iOS into a separate library and build the SDK around that, correct?

If that is true, this shouldn't be too much work. The main thing will be separating it out, creating a small sample project that uses it, and publishing to CocoaPods/Carthage.

**Comment by RohanNagar** [comment]
We can generate a Swift client library over on that repo using the new Swagger docs!

**Comment by RohanNagar** [comment]
A Swift (v3 and v4) client implementation can be generated using Swagger Generator with the latest Thunder Swagger (found at `/openapi.json` or `/openapi.yaml`).

We won't maintain a Swift SDK as any users can simply use the Swagger Generator or make REST calls directly.
