### ISSUE TITLE
JUnit 5 Migration

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#119]
Now that JUnit 5 has been out for some time, we can start thinking about upgrading.

Some resources:

https://junit.org/junit5/docs/current/user-guide/
http://www.baeldung.com/junit-5-migration
https://www.petrikainulainen.net/junit-5-the-ultimate-resource/#migrating-from-junit4
http://www.codingrevolution.com/junit-5-migration/

**Comment by NickEckert** [comment]
JUnit 5 is now used as of #171
