### ISSUE TITLE
Customize Email & Verification Success

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#135]
### This issue relates to a:

- [ ] Bug
- [x] Suggestion
- [ ] Feature Proposal

### Description:

The email message sent on `POST /verify` should be configured through the configuration. At the very least, it needs to contain an option on what the domain name is so that the link in the email is correct.

### Additional Information:
This issue was combined with #122. The verification and success pages will be pulled in as raw HTML instead of configurable properties to prevent restricting the structure of the page itself.

**Comment by NickEckert** [comment]
This was addressed in #147 and a new new related issue was made in #150.
