### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by NickEckert** [RohanNagar/thunder#137]
### This issue relates to a:

- [ ] Bug
- [x] Suggestion
- [x] Feature Proposal

### Description:
At some point it would be nice to sport HTTPS for communication between the server and client. We could allow users to utilize certificates purchased from a certificate authority or their own self signed certificate.

HTTPS allows encrypted communication to the server. This would be necessary in a production environments where users are sending credentials to the server. In many cases these password would be hashed but this still opens us up to dictionary/rainbow table attack on our users password hashes.

HTTP also allows users to verify the identity of Thunder servers. (see trust chaining below)

I would also like to point out that if a future goal is to have Thunder as a Service (TaaS) then a lack of HTTPS support would certainly scare aways a large number of potential users.  

### Additional Information:

https://en.wikipedia.org/wiki/HTTPS
https://en.wikipedia.org/wiki/Chain_of_trust
https://blog.instantssl.com/https/seo-advantages-switching-https/

**Comment by RohanNagar** [comment]
Huge +1 and I would like to target this for v2.0.0 so that it can be ready at the same time full customization is ready.

**Comment by RohanNagar** [comment]
Since Dropwizard supports HTTPS already, it looks like the main work item for this is:

- Testing it locally
- Updating deployment definitions (K8s YAML files, Dockerfile) to expose HTTPS port
- Extensive documentation on how to enable/disable it and bringing certificates

**Comment by RohanNagar** [comment]
Since this is already supported, documentation and testing for it will be on hold.
