### ISSUE TITLE
Move Validation Logic into PropertyValidator Class

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#149]
### This issue relates to a:

- [ ] Bug
- [x] Suggestion
- [ ] Feature Proposal

### Description:

The validation logic particularly in the `UserResource` is repeated across the methods. We can move the validation logic into its own class and make the code easier to read. This would also make the tests easier to understand and more logical.

**Comment by RohanNagar** [comment]
I have an idea of how to do this, so sync with me if you want to take this issue on.

Basically, move the logic to the `RequestValidator` class, create overloading methods

`validateRequest(User user)`

`validateRequest(String email, String password)`

`validateRequest(String email, String password, User user)`

These methods do the validation and if something is invalid, throw a `ValidationException`. The exception has a method to `buildResponse(String requestType)` and it will build the proper response (status code and response body) for the validation issue.

The resource methods can then call `validateRequest` and catch the exception, and return the result of `buildResponse`.

**Comment by RohanNagar** [comment]
@alexsuperdev please do! Feel free to let me know if you have any questions!

**Comment by RohanNagar** [comment]
@alexsuperdev Haha wow that's a lot! I actually use IntelliJ, not Eclipse. Perhaps you can try to create a formatter configuration from the Checkstyle configuration? See here for a possible answer on how to do it: https://stackoverflow.com/questions/984778/how-to-generate-an-eclipse-formatter-configuration-from-a-checkstyle-configurati

The Checkstyle configuration is the `checkstyle.xml` file in the root.

**Comment by alexsuperdev** [comment]
@RohanNagar I have done this issue locally and also corrected Checkstyle violations :) I could push my branch or attach here the classes for review

**Comment by RohanNagar** [comment]
Also let me know if you need help getting that up. You should be able to fork the repo, push to a branch on your fork, and then create the PR in Github (from your fork to this repo).

**Comment by alexsuperdev** [comment]
I had a little trouble, but after a while i suceeded with fork and push, thanks
