### ISSUE TITLE
Unsupported dynamic URLs in custom HTML pages

### ISSUE THREAD

**Issue by NickEckert** [RohanNagar/thunder#150]
### This issue relates to a:

- [ ] Bug
- [x] Suggestion
- [ ] Feature Proposal

### Description:

PR #135 added custom html pages but introduced a problem by preventing the inclusion of dynamic URL's in the html page. This makes it impossible for a user receiving a verification email to connect back to Thunder.

**Comment by RohanNagar** [comment]
Work is in progress on the `url` branch

**Comment by RohanNagar** [comment]
TODO still:

- [ ] Better handling of `baseUrl` configuration option
- [ ] Tests
- [ ] Cleanup

**Comment by RohanNagar** [comment]
Instead of the `baseUrl` configuration option, we can do better by using `@Context UriInfo uriInfo`

https://stackoverflow.com/questions/7652321/getting-the-base-url-of-my-server-with-jax-rs

**Comment by RohanNagar** [comment]
Will open a new PR for customizing the replacement string.
