### ISSUE TITLE
Make Javadoc Conform to Format

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#165]
**Description**

Continuation of #164. We need to agree on a format for all Javadoc and make the current documentation match the format.

**Additional context**

@NickEckert can you come up with a format and then I can review and we can agree on one?

Links:
http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
https://docs.oracle.com/javase/1.5.0/docs/api/java/util/Formatter.html

**Comment by NickEckert** [comment]
Yea I will create a new Wiki page that outlines JavaDoc format for the Thunder project.

**Comment by RohanNagar** [comment]
Would be great if we can settle on a good format. If we can find a standard format that many Java projects use that would be even better.

**Comment by RohanNagar** [comment]
After searching around, I found some extensive guidelines that we can base our guidelines off of: https://github.com/liferay/liferay-portal/blob/master/readme/JAVADOC_GUIDELINES.markdown

I will look into this in the next few weeks.
