### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#192]
**Description**

We need a new logo for Thunder.

**Additional context**

**Comment by RohanNagar** [comment]
@reallinfo Hi - this may be a long shot but I have noticed your work on other open source repositories where you have contributed a logo. I actually found you from your work here: https://github.com/genuinetools/pepper/pull/4

If you are still offering logos, I would love if you could consider creating one for this project, Thunder.

We have one currently in the README, but it is small and a bit outdated. We are wanting a logo that includes the name Thunder in it as well.

If you can help out that would be greatly appreciated! If not, I definitely understand.

**Comment by RohanNagar** [comment]
Thank you @reallinfo! I like the color and the font of the two on the left. Could you maybe experiment with using the cloud from the [current logo](https://github.com/RohanNagar/thunder/blob/master/application/src/main/resources/logo.png)?

I like the "T" as well, so maybe you can keep the two on the left and also add two with the same color and font but with a cloud in place of the "T". Just to see how it would look.

Once we decide I'll let you know where to put the files for a pull request!

**Comment by reallinfo** [comment]
I tried several versions with the cloud. How is these?

![thunder](https://user-images.githubusercontent.com/36298335/41501798-cf4c25d2-71b3-11e8-8e7f-4be2f1c4a4dc.jpg)

**Comment by RohanNagar** [comment]
I love it! Those look great! Would I be able to get 4 versions?

1. The top left one as it is
2. The bottom left one as it is
3. The bottom left one but with the "Thunder" words below it
4. The top left without the words

Just to have some variety.

It would be great if you could add these to `application/src/main/resources/` in a PR

**Comment by reallinfo** [comment]
I will send a pr for all the versions you want. Also, if you want, i can update the readme file.

**Comment by RohanNagar** [comment]
That would be great, thanks @reallinfo!

**Comment by reallinfo** [comment]
is this good for readme file?

![thunder](https://user-images.githubusercontent.com/36298335/41502291-932b74d4-71bf-11e8-9c81-1fad866ef26e.jpg)

**Comment by RohanNagar** [comment]
Yes that one is great

**Comment by reallinfo** [comment]
I sent a pr. Please check it.

https://github.com/RohanNagar/thunder/pull/193

If you need a logo for another project, feel free to say me. Or if you have friends who need logo for a github repository, you can direct me.

Best regards!

**Comment by RohanNagar** [comment]
Thank you so much @reallinfo! I will definitely let you know if there are any future projects.

All the best!
