### ISSUE TITLE
Verify User Email Account

### ISSUE THREAD

**Issue by NickEckert** [RohanNagar/thunder#21]
Thunder needs to validate an email by sending an email to a newly registered user or newly registered email for an existing user. Once Thunder can validate that a user has access to the registered email the registration process can finish.

The process will go something like this:
1. Start the validation process by creating a new user and denoting the associated email as unverified. If the user already exists then update the email and denote it as unverified.
2. Generate a unique hash and store it alongside the unconfirmed field in the DB.
3. Append the hash as a query param to a url that points to a validation endpoint on Thunder and send the url to the address you want to validate.
4. When Thunder receives an email with a hash, parse the hash and confirm the user is associated with the given hash.
5. Mark the email as valid in thunder.

Note that a user account can be viewed as unverified if the email is not verified. This can be useful for tracking down accounts that are registered but never verified.

**The end goal is to allow account recovery and general contact with our user base.**

- [x] Create `Email` class that contains: `String address`, `boolean verified`, `String verificationToken`
- [x] PilotUser is updated to use `Email email` instead of `String email`
- [x] PilotUser still has the String email address as the Dynamo primary key
- [x] Ability to generate a hash to store in the DB
- [ ] A class to handle sending of emails. This should generate the URL of the form `thunder.sanctionco.com/verify?email=XXX&token=XXX`
- [x] Create a new resource class to handle verification requests at the endpoint `/verify`. Perhaps called `VerificationResource`. Create a POST method that takes query params `email` and `token`
- [x] The new endpoint verifies the token matches the one stored for the user, and marks the email as now verified

**Comment by RohanNagar** [comment]
@NickEckert We need to discuss on what the DB will look like. Right now the primary key is email. With what you're proposing, we can't do that anymore. We may have to use ID as the primary key. This will require major changes across Thunder, Lightning, and Pilot.

This is what I would ideally like:

- New Resource class, perhaps called `VerificationResource` to implement the required verification endpoint.
- A class to help with email sending. This will send out the initial verification email.
- An `Email` class that contains: `String address`, `boolean verified`, `String verificationToken`
- PilotUser needs to have a `List` of `Email` objects.

**Comment by RohanNagar** [comment]
Updated the original issue comment to reflect the tasks we need to do.

**Comment by RohanNagar** [comment]
Partially done in #22, still need to send emails.

**Comment by RohanNagar** [comment]
Finished in #27
