### ISSUE TITLE
Verify email should return an HTML page to the user

### ISSUE THREAD

**Issue by NickEckert** [RohanNagar/thunder#28]
When a user clicks on the verification link through their email thunder should return a success HTML page for the user. Currently a PilotUser is returned providing no indication that the link worked as far as a user is concerned.

**Comment by RohanNagar** [comment]
I would like to achieve this by adding a query param flag to the endpoint, such as `response=json` or `response=html`. That way, our code can receive a `PilotUser` and make it easier to do testing and validation, and the users can receive an HTML page.

**Comment by RohanNagar** [comment]
We can take a look at this that may help with this issue: https://stackoverflow.com/questions/11637365/dropwizard-produce-both-html-and-json-from-the-same-class

**Comment by RohanNagar** [comment]
After thinking about this some more, I think the best option is to use a query param, and if the query param is requesting HTML, we redirect to some URL that serves HTML. The logic would become pretty complex if we try to do both in one method. So here's what I'm thinking:

1. Add `response_type` query param to `GET /verify`
2. Check the response type before sending the response in the method. If it is `json`, then return the normal response. If it is `html`, then redirect to `GET /verify/success`
3. In `/verify/success`, return HTML

This has the added benefit of being simple to understand and straightforward to implement.

**Comment by RohanNagar** [comment]
Started work on the [html](https://github.com/RohanNagar/thunder/tree/html) branch.

Still TODO:
- [ ] Perform the redirect
- [ ] Write a nice HTML template to return
- [ ] Add tests for `ResponseType` API model
- [ ] Fix existing `VerificationResource` unit tests
- [ ] Add new `VerificationResource` unit tests to cover new code paths
- [ ] Update the Java client
- [ ] Update Java client tests
- [ ] Update the JavaScript client
- [ ] Update the integration test scripts
- [ ] Update documentation

**Comment by RohanNagar** [comment]
This is done in #121. Added follow-up issues:

#122 - Use HTML Templates
RohanNagar/thunder-client-js#4 - Add support for HTML response in JS client
